### ISSUE TITLE
Story gets loaded twice resulting in missing controls

### ISSUE THREAD

**Issue by nakoyasha** [flipbook-labs/flipbook#205]
## Describe the bug
When loading a story file, the controls appear for a split second before disappearing:

https://user-images.githubusercontent.com/96925398/234022805-8fc8c2c7-8099-4f7d-a33e-eb875473b26c.mp4

Output shows that the story gets loaded twice; once with the proper controls, and the second with all of them being empty strings.
![image](https://user-images.githubusercontent.com/96925398/234020334-5b037729-6d97-494c-a296-bc2da4d20df8.png)

## Expected behavior
I expect the story file to get loaded once; and with proper controls.
## Steps to reproduce

Open this story file:
```lua
return {
	summary = "Test",
	controls = {
		Blood = 500,
		XP = 500,
		Victim = "OnlyTwentyCharacters",
	},
	story = function(Preview, Props)
		print(Props.controls)
		local Root = Instance.new("TextLabel")
		Root.Size = UDim2.fromScale(1, 1)
		Root.Parent = Preview
		Root.Text = `B${Props.controls.Blood} XP{Props.controls.XP} - {Props.controls.Victim}`

		return function()
			Root:Destroy()
		end
	end,
}
```

**Comment by vocksel** [comment]
This issue should be fixed in the v2.0.0 release. I'm going to close this out but feel free to reopen if it still occurs
