### ISSUE TITLE
Changing controls resets component's state

### ISSUE THREAD

**Issue by adam-drake1** [flipbook-labs/flipbook#208]
## Describe the bug

Changing control values causes component's state to be reset

## Expected behavior

The component should be re-rendered with different props rather then creating the component again from scratch

## Steps to reproduce

1. Run the following story:
```lua
local ClickCounter = Roact.Component:extend("ClickCounter")

function ClickCounter:init()
	self:setState({ count = 0 })
end

function ClickCounter:render()
	return Roact.createElement("TextButton", {
		Text = `Count: {self.state.count}`,
		Size = UDim2.fromOffset(75, 35),
		[Roact.Event.Activated] = function()
			if (self.props.isDisabled) then return end
			
			self:setState(function(state)
				return {
					count = state.count + 1
				}
			end)
		end
	})
end

return {
	summary = "The button's state is reset when the controls are toggled",
	controls = { isDisabled = false },
	story = function(props)
		return Roact.createElement(ClickCounter, props.controls)
	end,
}
```

2. Click the button 5 times to set state.count to 5
3. Toggle the isDisabled control, state.count will be 0

**Comment by Hexcede** [comment]
I feel like it would fix a lot of problems if controls were designed in a way where users could define their own update behaviours. Because, currently there is no signalling behaviour at all which makes it impossible to support controls for anything except manually for a limited number of frameworks.

For example:
```lua

local isDisabled = Value(false) -- Fusion

return {
	summary = "Example",
	controls = {
		isDisabled = {
			type = "boolean";
			update = function(newValue)
				isDisabled:set(newValue)
			end;
		}
	};
	story = function(props)
		-- only called once
	end;
}
```

**Comment by frqstbite** [comment]
@vocksel bump for this as well; without this feature, controls cannot interop w/ Fusion animations at all.

**Comment by vocksel** [comment]
In v2.0.0 this issue should be resolved for Fusion, though React may still experience it. I'm not super inclined to change this behavior for React but if there are any extra reasons to I'd be open to reconsider
