### ISSUE TITLE
Complains about CoreGui

### ISSUE THREAD

**Issue by fewkz** [flipbook-labs/flipbook#218]
## Describe the bug

it is giving warnings about coregui

## Expected behavior

not give warnings about coregui

## Steps to reproduce

1. install plugin

## Error message, screenshots, and extra context
![RobloxStudioBeta_2023-07-09_10-24-03](https://github.com/flipbook-labs/flipbook/assets/83943819/14984fb7-e8db-4b9b-b9c1-3231c26e5898)

also, the plugin doesn't work at all for me. not sure if it's related.

**Comment by vocksel** [comment]
This is something we should filter for. Possibly by omitting CoreGui and other internal services from searches for storybooks.

In the meantime, the reason you're getting this is likely from this Studio setting being enabled:
<img width="618" alt="Screenshot 2023-07-09 at 12 21 26 PM" src="https://github.com/flipbook-labs/flipbook/assets/3081936/e0338a28-9e1e-4429-ac1a-4b2c87154698">
If you don't have a pertinent need to dig around in CoreGui you can turn off that setting so you can use flipbook without the warning spam.

In terms of it not working at all for you, I'd need more info to be able to diagnose what's wrong
