### ISSUE TITLE
Update documentation link on devforum

### ISSUE THREAD

**Issue by flxwed** [flipbook-labs/flipbook#254]
## Describe the bug

The official the Flipbook [devforum post](devforum.roblox.com/t/2184387) contains a link claiming to be the Flipbook documentation site. This link actually points to an [inactive site on github pages](https://vocksel.github.io/flipbook)

> - [Learn how to use flipbook on the documentation site](https://vocksel.github.io/flipbook)

## Expected behavior

The devforum post should point to the new documentation site at https://flipbook-labs.github.io/flipbook/

**Comment by vocksel** [comment]
Thanks for catching this. I've updated the devforum post with the correct link
